RUN_NAME: 'cifar10_random'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True
GAMMA: 10

DATASET:
  NAME: 'cifar10'
  TRANSFORM_NAME: 'CLD-cifar10'

RANDOM:
  SEEDS: [1, 2, 3, 4, 5]
  NUM_SELECTED_SAMPLES: 40
